#!/bin/bash

set -e

./enable-bash-aliases
./enable-case-insensitive-tab-completion
./install-git
./install-gitk
./enable-git-aliases
./enable-git-custom-prompt
./install-vim
./install-curl
./install-additional-wallpapers
./install-xclip

cat ./post-install-info.txt
