#!/bin/bash

set -e

DEST=~/scripts

mkdir -p $DEST

if [ ! -f $DEST/git-custom-prompt.sh ]; then
    cp git-custom-prompt.sh $DEST

    echo "# Custom prompt showing git information when in repo directory" >> ~/.bashrc
    echo ". ~/scripts/git-custom-prompt.sh" >> ~/.bashrc
    echo "" >> ~/.bashrc
fi
