#!/bin/bash

set -e

if [ $(grep -c "[ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"" ~/.bashrc) -eq 0 ]
then
    echo "# load nvm (node version manager)" >> ~/.bashrc
    echo "export NVM_DIR=\"\$HOME/.nvm\"" >> ~/.bashrc
    echo "[ -s \"\$NVM_DIR/nvm.sh\" ] && . \"\$NVM_DIR/nvm.sh\"" >> ~/.bashrc
    echo "" >> ~/.bashrc
fi
