#!/bin/bash

set -e

if [ ! -f $HOME/.nvm/nvm.sh ]; then
    wget -qO- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

    . ~/.nvm/nvm.sh

    nvm install --lts
    nvm alias default stable
    nvm use default

    echo "Updating npm to the most recent version"
    npm install npm -g
fi
