#!/bin/bash

set -e

wget -qO- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

. ~/.nvm/nvm.sh

echo "Suggest completing the installation by running the following commands:"
echo ""
echo "nvm install <node_version>"
echo "nvm alias default <node_version>"
echo "nvm use default"
echo ""

echo "# update npm to the most recent version"
echo "npm install npm -g"
echo ""
