#!/bin/bash

set -e

which java && (echo "Java already installed, exiting..."; exit 0)

echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo /usr/bin/debconf-set-selections
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get update
sudo apt-get install -y oracle-java8-installer

echo ""
echo ""
echo ""
echo "Note:"
echo "If the installation fails due to being behind a proxy and/or prohibited"
echo "to add additonal ppa:s, download and install manually from:"
echo ""
echo "http://www.oracle.com/technetwork/java/javase/downloads/index.html"
echo ""
